# Generated by Django 5.2.1 on 2025-05-25 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('enfermedades', models.TextField(blank=True, null=True, verbose_name='Enfermedades o condiciones crónicas')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias conocidas')),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo de sangre')),
                ('tutor_legal', models.CharField(max_length=255, verbose_name='Tutor legal del menor')),
                ('telefono_emergencias', models.CharField(max_length=20, verbose_name='Teléfono para emergencias')),
                ('medico_cabecera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médico/Pediatra de cabecera')),
                ('centro_medico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro médico afiliado')),
                ('numero_hermanos', models.PositiveIntegerField(default=0, verbose_name='Hermanos en el colegio')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de contratación')),
                ('codigo_modular', models.CharField(max_length=20, unique=True, verbose_name='Código Modular')),
                ('codigo_colegio_profesores', models.CharField(max_length=20, unique=True, verbose_name='Código Colegio de Profesores')),
                ('cursos_dictados', models.TextField(help_text='Separar cursos por comas', verbose_name='Cursos a dictar')),
                ('telefono_emergencias', models.CharField(max_length=20, verbose_name='Teléfono para emergencias')),
                ('tipo_contrato', models.CharField(choices=[('PLANTA', 'Planta'), ('CONTRATADO', 'Contratado'), ('SUPLENTE', 'Suplente')], max_length=20, verbose_name='Tipo de contrato')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docentes',
            },
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
