# Generated by Django 5.2.1 on 2025-05-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotech', '0002_alumno_docente_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nivel_escolar_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
